from fpdf import FPDF
from datetime import datetime
import io

class PDFReportService:
    @staticmethod
    def generate_report(location, climate_data, assessment):
        """
        Generates a professional drought risk assessment report in PDF format.
        """
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_fill_color(46, 125, 50) # Primary green
        pdf.rect(0, 0, 210, 40, 'F')
        
        pdf.set_font("Helvetica", "B", 24)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 20, "DroughtSense AI", ln=True, align='C')
        pdf.set_font("Helvetica", "I", 12)
        pdf.cell(0, 10, "Early Warning Agricultural Intelligence", ln=True, align='C')
        
        pdf.set_text_color(0, 0, 0)
        pdf.ln(20)
        
        # Location Info
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, f"Report for: {location['display_name']}", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 5, f"Coordinates: {location['lat']}°N, {location['lon']}°E | Date: {datetime.now().strftime('%Y-%m-%d')}", ln=True)
        pdf.ln(10)
        
        # Risk Badge
        risk_colors = {
            "Low": (76, 175, 80),
            "Medium": (255, 152, 0),
            "High": (244, 67, 54),
            "Critical": (183, 28, 28)
        }
        r, g, b = risk_colors.get(assessment['risk_level'], (0,0,0))
        
        pdf.set_fill_color(r, g, b)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(60, 12, f"RISK LEVEL: {assessment['risk_level']}", ln=True, align='C', fill=True)
        pdf.ln(10)
        
        # Climate Summary
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "30-Day Climate Summary", ln=True)
        pdf.set_font("Helvetica", "", 12)
        pdf.cell(0, 8, f"- Average Temperature: {climate_data['temperature']}°C", ln=True)
        pdf.cell(0, 8, f"- Total Precipitation: {climate_data['precipitation']}mm", ln=True)
        pdf.cell(0, 8, f"- Avg Soil Moisture: {int(climate_data['soil_moisture'] * 100)}%", ln=True)
        pdf.ln(10)
        
        # AI Assessment
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "AI Risk Assessment", ln=True)
        pdf.set_font("Helvetica", "", 11)
        pdf.multi_cell(0, 7, assessment['explanation'])
        pdf.ln(10)
        
        # Recommendations
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Actionable Recommendations", ln=True)
        pdf.set_font("Helvetica", "", 11)
        for rec in assessment['recommendations']:
            pdf.multi_cell(0, 7, f"* {rec}")
        
        pdf.ln(10)
        
        # Citations
        if assessment.get('citations') and assessment['citations'] != "None":
            pdf.set_font("Helvetica", "B", 12)
            pdf.cell(0, 10, "Scientific Citations", ln=True)
            pdf.set_font("Helvetica", "I", 9)
            pdf.multi_cell(0, 5, assessment['citations'])

        # Footer
        pdf.set_y(-25)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, "This report is generated by an AI agent and should be used for advisory purposes only.", ln=True, align='C')
        pdf.cell(0, 5, "Powered by AMD MI300X & NASA POWER Data.", ln=True, align='C')
        
        # Return as bytes
        return pdf.output()
